### ISSUE TITLE
Wocker and xdebug

### ISSUE THREAD

**Issue by GeorgeBotsev** [wckr/wocker#25]
Hello, I have some problems enabling xdebug on a wocker instance.
I see that it is not included in the original Docker release that you are using.
Is there any plans for including xdebug and adding a basic configuration, that can allow us to use xdebug and debug remotely

**Comment by ixkaito** [comment]
Hi, it might be a good idea to include Xdebug in the Docker image.
But I'm a little busy recently. I'm not sure when it will be done.
Pull requests are welcome though.

**Comment by franz-josef-kaiser** [comment]
As intermediate solution you can use:
- `vagrant ssh` into the VM
- `docker ps` to see the running Docker container. Example:
  
  ```
  CONTAINER ID        IMAGE                  COMMAND                  CREATED             STATUS              PORTS                                        NAMES
  c0cdf0469639        wocker/wocker:latest   "/usr/bin/supervisord"   About an hour ago   Up About an hour    0.0.0.0:80->80/tcp, 0.0.0.0:3306->3306/tcp   wocker
  ```
- Run an interactive shell in your Container:
  
  ```
  docker exec -it wocker bash
  # Alternatively, as long as you only have one container:
  docker exec -it $(docker ps -q) bash
  ```
- Run `apt-get update` to update the source list for the package manager
- Run `apt-get install php5-dev` to install the Dev package for PHP5 – this is a prerequisite. Note that this will take some serious amount of additional space: 200MB+
- When prompeted for overwriting your current `php.ini`, hit `2` to keep your **local** version
- Now you have _Pecl_ available and can install XDebug: `pecl install xdebug`
- Find your `php.ini` with `php --ini`. You will see the additional ini files folder:
  
  ```
  Scan for additional .ini files in: /etc/php5/cli/conf.d
  ```
- Add a new ini include file for XDebug: 
  
  ```
  touch /etc/php5/cli/conf.d/30-xdebug.ini
  ```
- Install _Nano_ because `vi`/Vim is **_hard_** to use. (If you do not: Hit the keyboard until it starts to type. Then type the necessary lines. Then hit `Esc`, then `:wq` to exit and save.)
  
  ```
  apt-get install nano
  # In case `nano` or `/bin/nano` results in "Error opening terminal: unknown.", 
  # you will have to run the following command up front:
  export TERM=xterm
  ```
- Edit it and enable XDebug by linking the `.so` file as `zend_extension`. When you want remote debugging, you will have to read that up for your IDE or for the shell or whatever you use.
  
  ```
  nano /etc/php5/cli/conf.d/30-xdebug.ini
  # This is the first line for the file:
  zend_extension=/usr/lib/php5/20131226/xdebug.so
  xdebug.overload_var_dump = 1
  xdebug.var_disply_max_depth = -1
  xdebug.var_display_max_children = -1
  xdebug.var_display_max_data = 512
  xdebug.max_nesting_level = -1
  xdebug.collect_params = 4
  xdebug.profiler_enable_trigger = 1
  xdebug.profiler_enable = 0
  xdebug.remote_enable = 1
  xdebug.profiler_output_dir = "/tmp"
  xdebug.profiler_output_name = "cachegrind.out.%t-%s"
  ```
- Run `apt-get install php5-xdebug` to install XDebug for Apache as well
- Restart Apache with `service apache2 restart`
- Hit `php -v` to see `PHP v … with XDebug v2.4 …` or similar as result
- Run `php -m` to see the _Zend Module_ being enabled
- Add `phpinfo( INFO_MODULES );` in some php file to see if the XDebug module was included for Apache
- Clean up and free some space by removing the following packages that have been installed as dependencies of `php5-dev` (nearly the same amount as installed previously) – this is copy/paste:
  
  ```
  apt-get remove \
      autoconf automake autopoint autotools-dev binutils bsdmainutils build-essential bzip2 cpp \
      cpp-4.9 debhelper dh-php5 dpkg-dev fakeroot file g++ g++-4.9 gcc gcc-4.9 gettext \
      gettext-base groff-base intltool-debian libalgorithm-diff-perl libalgorithm-diff-xs-perl \
      libalgorithm-merge-perl libasan1 libasprintf-dev libasprintf0c2 libatomic1 libc-dev-bin \
      libc6-dev libcilkrts5 libcloog-isl4 libcroco3 libdpkg-perl libfakeroot \
      libfile-fcntllock-perl libgcc-4.9-dev libgettextpo-dev libgettextpo0 libglib2.0-0 libglib2.0-data \
      libgomp1 libisl10 libitm1 liblsan0 libltdl-dev libltdl7 libmail-sendmail-perl libmpc3 libmpfr4 \
      libpcre3-dev libpcrecpp0 libpipeline1 libquadmath0 libsigsegv2 libssl-dev libssl-doc \
      libstdc++-4.9-dev libsys-hostname-long-perl libtimedate-perl libtool libtsan0 libubsan0 \
      libunistring0 linux-libc-dev m4 make man-db manpages manpages-dev patch php-pear \
      php5-dev pkg-php-tools po-debconf shared-mime-info shtool xdg-user-dirs xz-utils \
      zlib1g-dev nano
  ```
- You can now `exit` from the Docker Container and then again from the Vagrant provisioned VM

**Comment by ixkaito** [comment]
Xdebug has been added to [v1.2](https://wckr.github.io/changelog/).
