### ISSUE TITLE
Why vagrant if its a docker?

### ISSUE THREAD

**Issue by neohunter** [wckr/wocker#47]
I don't get why you are using a Virtual Machine with Vagrant to use docker? wouldn't make more sense to just use docker without vagrant?

**Comment by ixkaito** [comment]
First, there weren't any native Docker engines for Mac and Windows when I started this project.
Second, Wocker has its own CLI. It's totally in the Virtual Machine because I don't want to make the host machine messy.

However, we have Docker for Mac/Windows and Docker Machine now. I'm finding the best way of this issue. Maybe Wocker will just use Docker without Vagrant in the future.
