### ISSUE TITLE
Symlink to theme folder possible or editing php.ini?

### ISSUE THREAD

**Issue by sthag** [wckr/wocker#65]
I tried to symlink a theme folder on windows but it does not show up in the wordpress theme selection.
I did not expect it to but my question is, if this would be possible.
That way I could develop my theme with a workflow which has folder structures like this somewhere else...
```
project
_build
_src
```
... and link the build folder into the wocker environment specifically the themes folder.

**Comment by ixkaito** [comment]
Hi @sthag,

I understand what you want to do, but unfortunately it is not possible.

The reason of this is: 
The original theme data are on your host machine (whindows) and maybe synced to the virtual machine if located in the `data` folder. However, they are not synced to the Wocker container because the container only mounts the wordpress folder.

**Comment by sthag** [comment]
Thanks for the explanation. I should have looked it up. You already answered a similar question some time ago.
There is another circumstance I'm wondering about. You talked about editing the php.ini file in [this issue](https://github.com/wckr/wocker/issues/20) some time ago. I tried the method using `vi` but it seems the linebreaking of the php.ini is not correctly displayed for me. I had a hard time trying to edit values but could not get it right.
Is there another possibility to edit the `php.ini` file?

**Comment by sthag** [comment]
I managed to edit the file. So everything's fine for now :) Thank you.
