### ISSUE TITLE
SSH Permission Denied (fresh install)

### ISSUE THREAD

**Issue by jbalke** [wckr/wocker#78]
Not a ssh guru by any means but followed the "Run a New Wocker Container" instructions and am getting the following:

PS C:\wocker> vagrant ssh
bargee@127.0.0.1: Permission denied (publickey,keyboard-interactive). 

This is on a fresh, new (and up-to-date) install of virtualbox, vagrant and wocker. Otherwise, the test site is running fine.

What am i missing?

**Comment by ixkaito** [comment]
@jbalke Did you run your shell as an admin? I'm afraid you have to do it on Windows.

**Comment by jbalke** [comment]
Sure did @ixkaito 

I can see that ssh works fine during provisioning but it just won't allow me to log in interactively.

**Comment by jbalke** [comment]
Ok I have an update...

Using putty (converting the private_key), I logged into wocker fine.

I did attempt to troubleshoot via the windows beta ssh client, got a warning about the private_key being unprotected and that it would be ignored. After tightening up the permissions I then got an error about the key being an invalid format... hence resorting to putty.

This is all on a fresh Windows 10 Pro install, along with vagrant, virtualbox and wocker... i basically had to rebuild my PC prior to setting up my wordpress dev env. Ran the powershell console as Admin the whole time, shouldn't be this difficult but happy enough with the workaround.

**Comment by ixkaito** [comment]
@jbalke Glad to hear it. If you still have any troubles, just let me know 🙂

**Comment by JayOwl** [comment]
I had a similar problem. I had to use GitBash to access the the ssh. 

1. Use Gitbash
2. Go to Wocker install directory.
2. `vagrant up`
3. Once finished, `vagrant ssh`
4. You have to start wocker, `wocker run`
5. Go to wocker.test.

Thats what worked for me, hopefully this helped someone out. 

I have to repeat the `vagrant ssh` and `wocker run` step which kinda sucks coming from VVV. I'm trying  this out since every-time there seems to be an update for VVV, it breaks and I have to reinstall everything, its annoying to do once every 2 months or so.
